name: profile
description: A new Flutter project.


version: 1.1.2+3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.2
  flutter_svg: ^1.0.0
  url_launcher: ^6.0.17
  provider: ^6.0.1

  # Firebase packages
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  http: ^0.13.4
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  on_click: ^1.1.3
  flutter_screenutil: ^5.3.1
  fluttertoast: ^8.0.9
  get_storage: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  device_preview: ^1.0.0


flutter:
  generate: true

  uses-material-design: true

  # Assets
  assets:
    - assets/icons/
    - assets/images/


  # Fonts
  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
